config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/picture/new', to: 'pictures#new'
  get '/pictures', to: 'pictures#index'
  resources :users, :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    # create an "association" with user.rb
    belongs_to :user
    has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
   
    # create an "association" with picture.rb
    has_many :pictures, dependent: :destroy

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end 

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end 
    
    def authenticated?(remember_token)
        return false if remember_digest.nil? 
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.where(:user_id => current_user_id)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user_id
    respond_to do |format|
      if @picture.save

        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(images: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or pictures_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url 
  end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show 
    @user = User.find(params[:id])
  end 

  def new
    @user = User.new 
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Dizzy Image Repo!"
      redirect_to pictures_url #could also use redirect_to user_url(@user)
    else 
      render 'new'
    end 
  end 

  def edit
    @user = User.find(params[:id])
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user 
    else
      render 'edit'
    end
  end 

    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end 
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
      # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper# Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Image Repository"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end
        # Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # Returns the current logged-in user (if any).
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    # returns the current logged in user's ID
    def current_user_id 
        session[:user_id]
    end 

    def current_user?(user)
        user && user == current_user
    end 
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    # Logs out the current user.
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Check out <a href="https://github.com/noah40povis">Noah's github</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", '#' %></li>
            <li><%= link_to "Contact", 'noah.povis@gmail.com' %></li>
            
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
    <div class="container">
        <%= link_to "Noah's Image Repo", '#', id: "logo" %>
        <nav>
            <ul class="nav">
                <% if logged_in? %> 
                    <li><%= link_to "Gallery", pictures_url %></li>
                    <li><%= link_to "Upload Image", new_picture_url %></li> 
                
                    <li class="dropdown">
                        <button class="dropbtn">Account 
                        <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <%= link_to "Profile", current_user %>
                            <%= link_to "Settings", edit_user_path(current_user) %>
                            <%= link_to "Log out", logout_path, method: :delete %>
                        </div>
                    </li>
                <% else %>
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development?%> 
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= form.label :images %>
  <%= form.file_field :images, multiple: true %> 


  <div class="actions">
    <br> 
    <%= form.submit 'Upload' %> </br> 
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Pictures</h1> 
<h2><%= @pictures.count %> Uploded Pictures</h2>

<table>
<tbody>
<div class="container">
  <div class="row">
    <% @pictures.each do |picture| %>
          
            
            <% picture.images.each do |image|%>
              <div class="col-md-4">
              <div class="card h-100">
              <%= image_tag(image, class:'card-img') %>
              <div class="card-body">
              <p><%= link_to 'Show', picture %></p>
              <p><%= link_to 'Edit', edit_picture_path(picture) %></p>
              <p><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></p>
              </div> 
            </div>
            </div>
            <% end %>
          
    <% end %>
    </div>
    </div>
    </tbody>

</table>


<%= link_to 'Upload New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_url %>

app/views/pictures/show.html.erb
<p>
</p>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @picture.images.each do |image|%>
    <div class="col">
      <div class="card h-100">
        <%= image_tag(image, class:'card-img') %>
        <div class="card-body">
        <%= link_to 'Delete', @picture, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div> 
      </div>
    </div>
  <% end %>
  </div>
<p>

</p>
<%= link_to 'Back', pictures_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
        <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="container">
<p><%= render 'form' %></p>
</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col">
        <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>